name: test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'playground/**'
      - 'examples/**'

  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'playground/**'
      - 'examples/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Cache firebase tools
        id: cache-firebase-tools
        uses: actions/cache@v3
        env:
          cache-name: cache-firebase-tools
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Install firebase-tools
        run: pnpm add -g firebase-tools

      - name: Lint
        run: pnpm run lint

      - name: Types
        run: pnpm run test:types

      - name: Test
        run: firebase emulators:exec 'pnpm run test:unit'

      - name: Build
        run: pnpm run build

      - name: Nuxt module build
        run: pnpm run -C packages/nuxt build

      - uses: codecov/codecov-action@v2
